### ISSUE TITLE
AttributeError on event processing

### ISSUE THREAD

**Issue by Conway** [plusplusslack/pluspl.us#18]
Stack trace from Heroku:

```
2019-05-09T22:04:31.192727+00:00 app[web.1]: [2019-05-09 22:04:31,191] ERROR in app: Exception on /slack/events [POST]
2019-05-09T22:04:31.192736+00:00 app[web.1]: Traceback (most recent call last):
2019-05-09T22:04:31.192738+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
2019-05-09T22:04:31.192739+00:00 app[web.1]:     response = self.full_dispatch_request()
2019-05-09T22:04:31.192749+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
2019-05-09T22:04:31.192750+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2019-05-09T22:04:31.192751+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
2019-05-09T22:04:31.192752+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2019-05-09T22:04:31.192753+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
2019-05-09T22:04:31.192755+00:00 app[web.1]:     raise value
2019-05-09T22:04:31.192756+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
2019-05-09T22:04:31.192757+00:00 app[web.1]:     rv = self.dispatch_request()
2019-05-09T22:04:31.192758+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
2019-05-09T22:04:31.192760+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2019-05-09T22:04:31.192761+00:00 app[web.1]:   File "/app/plusplus/slackeventsapi/slackserver.py", line 122, in event
2019-05-09T22:04:31.192763+00:00 app[web.1]:     self.emitter.emit(event_type, *event_args)
2019-05-09T22:04:31.192764+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/pyee/_base.py", line 102, in emit
2019-05-09T22:04:31.192765+00:00 app[web.1]:     self._emit_run(f, args, kwargs)
2019-05-09T22:04:31.192766+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/pyee/_compat.py", line 48, in _emit_run
2019-05-09T22:04:31.192767+00:00 app[web.1]:     coro = f(*args, **kwargs)
2019-05-09T22:04:31.192768+00:00 app[web.1]:   File "/app/plusplus/app.py", line 39, in handle_message
2019-05-09T22:04:31.192770+00:00 app[web.1]:     process_incoming_message(event_data, req)
2019-05-09T22:04:31.192771+00:00 app[web.1]:   File "/app/plusplus/operations/slack_handler.py", line 20, in process_incoming_message
2019-05-09T22:04:31.192772+00:00 app[web.1]:     message = event.get('text').lower()
2019-05-09T22:04:31.192773+00:00 app[web.1]: AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by Conway** [comment]
Hasn't been observed lately
